# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "hidepay-b2-bby-retrospec"
client_id = "49074be3c45d1ee58be344d8012e663f"
application_url = "https://ddr-dx-spots-tim.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_payment_customizations,read_payment_customizations"

[auth]
redirect_urls = [
  "https://ddr-dx-spots-tim.trycloudflare.com/auth/callback",
  "https://ddr-dx-spots-tim.trycloudflare.com/auth/shopify/callback",
  "https://ddr-dx-spots-tim.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "retrospecdevelopmentstore.myshopify.com"
